# Theme app extension - Delivery Date Estimator
# https://shopify.dev/docs/apps/build/online-store/theme-app-extensions/configuration

api_version = "2024-10"

[[extensions]]
uid = "4fe319d8-217d-44e9-49cf-fa1dd60574a0cf32cf19"
type = "theme"
name = "Delivery Date Widget"
handle = "delivery-date-widget"
description = "Shows estimated delivery date and optional countdown on product pages."
